//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public Nullable<int> Team1Id { get; set; }
        public Nullable<int> Team2Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Team1Goals { get; set; }
        public Nullable<int> Team2Goals { get; set; }
        public string Stage { get; set; }
        public bool OpenForBet { get; set; }
        public string Team1Name { get; set; }
        public string Team2Name { get; set; }
    }
}
