//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBet
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBet
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> UserTeam1Goals { get; set; }
        public Nullable<int> UserTeam2Goals { get; set; }
        public Nullable<int> Points { get; set; }
    }
}
